added description_for_merchant
ThePay/api-client pull request #10
Opened 2022-04-04 08:27 UTC by AlexKratky

http://redmine.havelholding.cz/issues/3981

2022-04-04 09:52 UTC, Triplkrypl requested changes

2022-04-04 09:52 UTC, Triplkrypl commented on src/Model/SimplePayment.php
> +     * @return string
return type is incorrect, private property can contains `string|null`

2022-04-04 09:52 UTC, Triplkrypl commented on src/Model/SimplePayment.php
> +        $this->description_for_merchant = $data['description_for_merchant'];
This is break change, it is somethink like new required parameter. If some one use `SimplePayment` contructor for some reason, without this key his code will crash.
Add some check if `description_for_merchant` key realy exist in input array.

2022-04-04 09:59 UTC, Triplkrypl commented
New response parameter is not realeaset yet, change target branche in to `v1.x-stage`.

2022-04-04 11:03 UTC, AlexKratky commented
> 

but there is not v1.x-stage, only v1.x-spring and this is for summer release https://github.com/ThePay/api-client/branches/all and I am not sure how to create branch to keep checks (one approval etc.)

2022-04-04 11:51 UTC, Triplkrypl commented
We have checks for all branches started with **v**, but if we fix break change here, we can release new PHP property without deploying changes on our server. SDK always return null until we kick out new release but merchants developers can implement new interface simultaneously, while we testing new features. This can speed-up integration process.

2022-04-06 17:01 UTC, Triplkrypl requested changes
Break change in SimplePayment is not fixed.

2022-04-07 13:16 UTC, AlexKratky commented
> Break change in SimplePayment is not fixed.

but if we release it with summer release, there will be that key in response, so no need to check if key exists, otherwise I can add key exist check, but then we can merge it to v1.x

2022-04-07 13:50 UTC, Triplkrypl commented
Yes we will always send `description_for_merchant` key in response, but everyone could create `SimplePayment` object in their project for some creative reason, we can not prevent of call the constructor outside of our library.
So new required input key can break some code, i hope only unit tests where instance can be used as dummy mock.
This break changes not affect main interface for developers, but we can not predict how they use our code, i truly recommend check new array key and have new feature without break change as possible.

2022-04-13 08:17 UTC, AlexKratky commented
> Yes we will always send `description_for_merchant` key in response, but everyone could create `SimplePayment` object in their project for some creative reason, we can not prevent of call the constructor outside of our library. So new required input key can break some code, i hope only unit tests where instance can be used as dummy mock. This break changes not affect main interface for developers, but we can not predict how they use our code, i truly recommend check new array key and have new feature without break change as possible.

Well now I understand, however it is not documented to use it like that. Every change in input/output of any method could be BC, even after adding check if key is set, someone can have a test, that will check count of key of method toArray() for example

2022-04-13 10:23 UTC, Triplkrypl approved these changes

2022-04-13 10:59 UTC, merged