deprecated php versions removed and phpunit update
ThePay/api-client pull request #44
Opened 2023-06-13 17:03 UTC by Triplkrypl

https://redmine.havelholding.cz/issues/4649

2023-06-14 10:50 UTC, joseftraxler commented on tests/CreatePaymentTest.php
> +        self::assertTrue(get_class($result) === 'ThePay\ApiClient\Model\CreatePaymentResponse');
Tady by se možná hodilo nahradit ten řetězec za `CreatePaymentResponse::class`

2023-06-14 10:52 UTC, joseftraxler commented on tests/CreatePaymentTest.php
> +        self::assertTrue(get_class($result) === 'ThePay\ApiClient\Model\CreatePaymentResponse');
Navíc místo assertTrue by se zde spíše hodilo použít např. `self::assertSame($result::class, CreatePaymentResponse::class);`, aby to v případě failu vrátilo relevantnější informace.

2023-06-14 10:54 UTC, joseftraxler commented on tests/HttpCurlServiceTest.php
> +        self::assertEquals('ThePay\ApiClient\Http\HttpResponse', get_class($response));
Tady také jak jsme psal výše.

2023-06-14 10:57 UTC, joseftraxler commented on tests/PaymentMethodsTest.php
> +        self::assertSame(array('online', 'returnable'), $cardMethod->getTags());
Na pole bych používal jen zkrácený zápis: `['online', 'returnable']`, `['CZK']`. Myslím, že to tak i IDE napovídá.

2023-06-14 11:01 UTC, joseftraxler commented on tests/RealizeSavedAuthorizationPaymentTest.php
> +        self::assertTrue(get_class($result) === 'ThePay\ApiClient\Model\ApiResponse');
Opět jako výše

2023-06-14 11:02 UTC, joseftraxler commented on tests/RealizeSubscriptionPaymentTest.php
> +        self::assertTrue(get_class($result) === 'ThePay\ApiClient\Model\ApiResponse');
No asi by to chtělo projít i další místa, raději už nebudu všechna označovat.

2023-06-14 11:10 UTC, joseftraxler commented on tests/ValueObjectTest.php
> +    public function testIdentifierInvalidValues(string $id): void
Tento test má podle mě zbytečný dataprovider, dělá jednoduchou věc, jen zkontroluje, že při vstupu velkého řetězce vrátí konkrétní hlášku, to nemá smysl komplikovat rovnou bych to upravil na:
```php
    public function testIdentifierInvalidValues(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Value\'s length has to be up to 100 characters');
        Identifier::create(self::randomChars(101));
    }
```
A pak ten dataprovider zruš.

2023-06-14 11:12 UTC, joseftraxler commented on tests/ValueObjectTest.php
> +    public function testLanguageCode(string $code): void
Časem by bylo dobré ty jednotlivé ValueObjects rozdělit na samostatné testy pro každý zvlášť, ale to teď řešit nemusíme.

2023-06-14 11:15 UTC, joseftraxler requested changes
Vypadá to dobře, ale těch pár drobností, co jsem tu připsal bych chtěl, abychom ještě upravili.

2023-06-16 15:18 UTC, Triplkrypl commented on tests/PaymentMethodsTest.php
> +        self::assertSame(array('online', 'returnable'), $cardMethod->getTags());
Y, i was surprised, i fixed in IDE, but fixer change it back before i made push.
So i update fixer rules on something more uptodate here: #45 and fix all files in repo.

2023-06-16 15:21 UTC, joseftraxler commented on tests/PaymentMethodsTest.php
> +        self::assertSame(array('online', 'returnable'), $cardMethod->getTags());
Amazing

2023-06-20 06:59 UTC, joseftraxler approved these changes
Very good job 👍

2023-06-20 11:42 UTC, merged