Refactored value objects
ThePay/api-client pull request #72
Opened 2024-08-26 13:18 UTC by petrknap

https://redmine.havelholding.cz/issues/1951

2024-08-26 13:21 UTC, petrknap commented on src/ValueObject/CountryCode.php
> +        $countryCodeCandidate = strtoupper(trim($nonEmptyString));
Is it okay to apply `strtoupper`?

2024-08-26 13:21 UTC, petrknap commented on src/ValueObject/CurrencyCode.php
> +        $currencyCodeCandidate = strtoupper(trim($nonEmptyString));
Is it okay to apply `strtoupper`?

2024-08-26 13:22 UTC, petrknap commented on src/ValueObject/EnumValueObject.php
> +    abstract public static function cases(): array;
Renamed to met <https://www.php.net/manual/en/unitenum.cases.php>

2024-08-26 13:25 UTC, petrknap commented on src/ValueObject/LanguageCode.php
> +        $languageCodeCandidate = strtolower(trim($nonEmptyString));
Is it okay to apply `strtolower`?

2024-08-26 13:28 UTC, petrknap commented on src/ValueObject/SecureUrl.php
> +            throw self::invalidValue('"https://" prefixed', $url);
Any idea for better message? `"https://" prefixed URL`?

2024-08-26 15:01 UTC, Triplkrypl commented on src/ValueObject/CountryCode.php
> +        $countryCodeCandidate = strtoupper(trim($nonEmptyString));
We can remove conversion and validate input string only for upper case characters.
With validation we can prevent language substitution by mistake, example 'sk' language is not 'SK' country, this is reason why ISO language is lower case and ISO countries is upper case.

2024-08-26 15:01 UTC, Triplkrypl commented on src/ValueObject/SecureUrl.php
> +            throw self::invalidValue('"https://" prefixed', $url);
One example for inspiration: https://github.com/simple-as-fuck/php-validator/blob/44f2b59996e52d571c5534476a4cdba6760fa6e6/src/Rule/Url/UrlRule.php#L79.
I not have better idea.

2024-08-26 19:14 UTC, joseftraxler requested changes
I just wanna rename filter method to something better. All changes have tests, well done 👍.

2024-08-26 19:14 UTC, joseftraxler commented on src/ValueObject/BaseValueObject.php
> +    abstract protected static function filter($value);
Why does it name filter? I'd like to rename it to `adjustValue` or `validateAndAdjustValue` or something like this.
```suggestion
    abstract protected static function validateAndAdjustValue($value);
```

2024-08-26 19:14 UTC, joseftraxler commented on src/ValueObject/CurrencyCode.php
> +        $currencyCodeCandidate = strtoupper(trim($nonEmptyString));
Don't know why not. IMHO it's OK.

2024-08-26 19:14 UTC, joseftraxler commented on src/ValueObject/BaseValueObject.php
>       * @param TValue|mixed $value
```suggestion
     * @param mixed $value
```
mixed is enough

2024-08-27 06:55 UTC, petrknap commented on src/ValueObject/BaseValueObject.php
> +    abstract protected static function filter($value);
Method `filter` refers to <https://www.php.net/manual/en/function.filter-var.php> - in ideal world the implementation should be like:

```php
protected static function filter(mixed $value): int
{
    $intCandidate = filter_var($value, FILTER_VALIDATE_INT);
    if ($intCandidate === false) {
        throw self::invalidValue('int');
    }
    return $intCandidate;
}
```

2024-08-27 12:30 UTC, joseftraxler commented on src/ValueObject/BaseValueObject.php
> +    abstract protected static function filter($value);
OK, i don't wanna waste my time, so keep it as you wish.

2024-08-27 12:31 UTC, joseftraxler approved these changes

2024-08-27 14:46 UTC, Triplkrypl approved these changes

2024-08-28 07:59 UTC, merged